spring.application.name=userManagement-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/platform-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.config.import=optional:configserver:http://localhost:8888/

app.keycloak.admin.clientId=PlateForme_client
app.keycloak.admin.clientSecret=Fii3laKp5DD5Oyu47UupRUW6I80b9EhZ
app.keycloak.realm=PlateForme
app.keycloak.serverUrl=http://localhost:8080
spring.cloud.consul.discovery.prefer-ip-address=true